GET http://localhost:3333/api/products

###
GET http://localhost:3333/api/products/5effab9c562922181ae2818c

###
POST http://localhost:3333/api/products
Content-Type: application/json

{
    "title" : "teste 2",
    "description" : "teste description 2",
    "url" : "teste url 2"
}

###
PUT http://localhost:3333/api/products/5effab9c562922181ae2818c
Content-Type: application/json

{
    "title" : "Iphone 11 Pro Max",
    "Description" : "Apple Smartphone",
    "url": "https://www.apple.com/br/iphone-11-pro-max/"
}

###
DELETE http://localhost:3333/api/products/5f0cf8ecc2dca018132db833